spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiss_db
    username: henrique
    password: senha
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true