spring:
  datasource:
    url: jdbc:postgresql://172.23.37.74:5432/tiss_ops_gateway
    username: henrique
    password: testesql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    # Usa as mesmas credenciais do datasource
    user: henrique
    password: testesql